#!/bin/bash

# Usage: $0 [options] base-dir s3://url [prefix]

# Fail if anything does
set -e

basedir=$1
s3url=$2
prefix=$3

fsck.s3ql "$s3url"

s3qlmnt=$(mktemp -d -t s3ql-backup-XXXXXXXXX)

mount.s3ql --compress=zlib --compression-threads=2 "$s3url" "$s3qlmnt"

s3qldir="$s3qlmnt/$prefix"
[ -n "$prefix" ] && mkdir -p "$s3qldir"

trap "cd /; sleep 3; umount.s3ql $s3qlmnt; rmdir $s3qlmnt" EXIT

datedir="$s3qldir/$(date -u +%Y-%m-%d)"
mostrecent="$(ls -1r $s3qldir | egrep '[0-9]{4}-[0-9]{2}-[0-9]{2}' | head -1)"

if [ -n "$mostrecent" -a "$s3qldir/$mostrecent" != "$datedir" ]; then
	s3qlcp "$s3qldir/$mostrecent" "$datedir"
fi

[ ! -d "$datedir" ] && mkdir -p "$datedir"

rsync -aHAXxR --delete-during --delete-excluded --partial -v \
	--exclude '*~' \
		 "$basedir" "$datedir"

#s3qllock "$datedir"
